### ISSUE TITLE
Error message showing when when saving a new note

### ISSUE THREAD

**Issue by LebohangT** [majortank/smartnotes#9]
Please take note that there might be a bug on the code, when saving a note I receive an error message "Field is required" even though I have filled in all the open fields.
![error screenshot](https://github.com/user-attachments/assets/0390aecf-ba38-48af-b11d-b9f702030117)

**Comment by majortank** [comment]
### Hi Sorry I forgot to automate/fix that 
### The issue is:

Categories are not created automatically when running migrations!

As you can see they are empty:
![image](https://github.com/user-attachments/assets/e48fea53-8e13-4f75-a034-825a29fb991e)


# After setting up your project which is after running these:
```bash
pip install -r requirements.txt
```
```bash
python manage.py migrate
```

# In your Terminal in the project folder
## Run this for Categories

```bash 
python manage.py shell
```
## This will create the categories
```python
from notes.models import Category

CATEGORY_CHOICES = [
    ('Personal', 'Personal'),
    ('Work', 'Work'),
    ('School/Education', 'School/Education'),
    ('Shopping', 'Shopping'),
    ('Travel', 'Travel'),
    ('Recipes', 'Recipes'),
    ('Health/Fitness', 'Health/Fitness'),
    ('Finance', 'Finance'),
    ('Projects', 'Projects'),
    ('Ideas', 'Ideas'),
]

for choice in CATEGORY_CHOICES:
    Category.objects.get_or_create(name=choice[0])

exit
```

```bash
python manage.py runserver
```

## refresh the page and now you can pick a category and create a note

![image](https://github.com/user-attachments/assets/28dbe258-3c2d-4519-aa6e-b284b9d22e08)



# This is what you need to do in the terminal

![image](https://github.com/user-attachments/assets/342bfdd3-d489-4399-bad6-1564f6ad2209)

## Anyway I will make fix to create the categories automatically thanks for the HeadsUp
